### ISSUE TITLE
Release v0.0.3 to GitHub

### ISSUE THREAD

**Issue by andriesfc** [DarkGrayMatter/sec#44]
# Todo

- [x] Bump up to version 0.0.3
- [x] modify build file to publish direct to GitHub
- [ ] Draw up release notes.
- [ ] Review/Cleanup readme
